// Generated by gencpp from file arm_lib/FK.msg
// DO NOT EDIT!


#ifndef ARM_LIB_MESSAGE_FK_H
#define ARM_LIB_MESSAGE_FK_H

#include <ros/service_traits.h>


#include <arm_lib/FKRequest.h>
#include <arm_lib/FKResponse.h>


namespace arm_lib
{

struct FK
{

typedef FKRequest Request;
typedef FKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FK
} // namespace arm_lib


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm_lib::FK > {
  static const char* value()
  {
    return "5bfba77d79999ef10d63e1c6532bc662";
  }

  static const char* value(const ::arm_lib::FK&) { return value(); }
};

template<>
struct DataType< ::arm_lib::FK > {
  static const char* value()
  {
    return "arm_lib/FK";
  }

  static const char* value(const ::arm_lib::FK&) { return value(); }
};


// service_traits::MD5Sum< ::arm_lib::FKRequest> should match
// service_traits::MD5Sum< ::arm_lib::FK >
template<>
struct MD5Sum< ::arm_lib::FKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm_lib::FK >::value();
  }
  static const char* value(const ::arm_lib::FKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_lib::FKRequest> should match
// service_traits::DataType< ::arm_lib::FK >
template<>
struct DataType< ::arm_lib::FKRequest>
{
  static const char* value()
  {
    return DataType< ::arm_lib::FK >::value();
  }
  static const char* value(const ::arm_lib::FKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm_lib::FKResponse> should match
// service_traits::MD5Sum< ::arm_lib::FK >
template<>
struct MD5Sum< ::arm_lib::FKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm_lib::FK >::value();
  }
  static const char* value(const ::arm_lib::FKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_lib::FKResponse> should match
// service_traits::DataType< ::arm_lib::FK >
template<>
struct DataType< ::arm_lib::FKResponse>
{
  static const char* value()
  {
    return DataType< ::arm_lib::FK >::value();
  }
  static const char* value(const ::arm_lib::FKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_LIB_MESSAGE_FK_H
