// Generated by gencpp from file arm_lib/FKRequest.msg
// DO NOT EDIT!


#ifndef ARM_LIB_MESSAGE_FKREQUEST_H
#define ARM_LIB_MESSAGE_FKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_lib
{
template <class ContainerAllocator>
struct FKRequest_
{
  typedef FKRequest_<ContainerAllocator> Type;

  FKRequest_()
    : joint_angles()  {
    }
  FKRequest_(const ContainerAllocator& _alloc)
    : joint_angles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _joint_angles_type;
  _joint_angles_type joint_angles;





  typedef boost::shared_ptr< ::arm_lib::FKRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_lib::FKRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FKRequest_

typedef ::arm_lib::FKRequest_<std::allocator<void> > FKRequest;

typedef boost::shared_ptr< ::arm_lib::FKRequest > FKRequestPtr;
typedef boost::shared_ptr< ::arm_lib::FKRequest const> FKRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_lib::FKRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_lib::FKRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_lib::FKRequest_<ContainerAllocator1> & lhs, const ::arm_lib::FKRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joint_angles == rhs.joint_angles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_lib::FKRequest_<ContainerAllocator1> & lhs, const ::arm_lib::FKRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_lib

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_lib::FKRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_lib::FKRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::FKRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::FKRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::FKRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::FKRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_lib::FKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9eebf9cc7d525d143ad033b65dacb648";
  }

  static const char* value(const ::arm_lib::FKRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9eebf9cc7d525d14ULL;
  static const uint64_t static_value2 = 0x3ad033b65dacb648ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_lib::FKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_lib/FKRequest";
  }

  static const char* value(const ::arm_lib::FKRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_lib::FKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] joint_angles\n"
;
  }

  static const char* value(const ::arm_lib::FKRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_lib::FKRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FKRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_lib::FKRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_lib::FKRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_angles[]" << std::endl;
    for (size_t i = 0; i < v.joint_angles.size(); ++i)
    {
      s << indent << "  joint_angles[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_angles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_LIB_MESSAGE_FKREQUEST_H
