// Generated by gencpp from file arm_lib/IK.msg
// DO NOT EDIT!


#ifndef ARM_LIB_MESSAGE_IK_H
#define ARM_LIB_MESSAGE_IK_H

#include <ros/service_traits.h>


#include <arm_lib/IKRequest.h>
#include <arm_lib/IKResponse.h>


namespace arm_lib
{

struct IK
{

typedef IKRequest Request;
typedef IKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IK
} // namespace arm_lib


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm_lib::IK > {
  static const char* value()
  {
    return "1ddfd34f87b4b1bd0603440253b8c447";
  }

  static const char* value(const ::arm_lib::IK&) { return value(); }
};

template<>
struct DataType< ::arm_lib::IK > {
  static const char* value()
  {
    return "arm_lib/IK";
  }

  static const char* value(const ::arm_lib::IK&) { return value(); }
};


// service_traits::MD5Sum< ::arm_lib::IKRequest> should match
// service_traits::MD5Sum< ::arm_lib::IK >
template<>
struct MD5Sum< ::arm_lib::IKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm_lib::IK >::value();
  }
  static const char* value(const ::arm_lib::IKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_lib::IKRequest> should match
// service_traits::DataType< ::arm_lib::IK >
template<>
struct DataType< ::arm_lib::IKRequest>
{
  static const char* value()
  {
    return DataType< ::arm_lib::IK >::value();
  }
  static const char* value(const ::arm_lib::IKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm_lib::IKResponse> should match
// service_traits::MD5Sum< ::arm_lib::IK >
template<>
struct MD5Sum< ::arm_lib::IKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm_lib::IK >::value();
  }
  static const char* value(const ::arm_lib::IKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_lib::IKResponse> should match
// service_traits::DataType< ::arm_lib::IK >
template<>
struct DataType< ::arm_lib::IKResponse>
{
  static const char* value()
  {
    return DataType< ::arm_lib::IK >::value();
  }
  static const char* value(const ::arm_lib::IKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_LIB_MESSAGE_IK_H
