// Generated by gencpp from file arm_lib/IKRequest.msg
// DO NOT EDIT!


#ifndef ARM_LIB_MESSAGE_IKREQUEST_H
#define ARM_LIB_MESSAGE_IKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_lib
{
template <class ContainerAllocator>
struct IKRequest_
{
  typedef IKRequest_<ContainerAllocator> Type;

  IKRequest_()
    : actuator_pose()
    , joint_positions()  {
    }
  IKRequest_(const ContainerAllocator& _alloc)
    : actuator_pose(_alloc)
    , joint_positions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _actuator_pose_type;
  _actuator_pose_type actuator_pose;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _joint_positions_type;
  _joint_positions_type joint_positions;





  typedef boost::shared_ptr< ::arm_lib::IKRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_lib::IKRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IKRequest_

typedef ::arm_lib::IKRequest_<std::allocator<void> > IKRequest;

typedef boost::shared_ptr< ::arm_lib::IKRequest > IKRequestPtr;
typedef boost::shared_ptr< ::arm_lib::IKRequest const> IKRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_lib::IKRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_lib::IKRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_lib::IKRequest_<ContainerAllocator1> & lhs, const ::arm_lib::IKRequest_<ContainerAllocator2> & rhs)
{
  return lhs.actuator_pose == rhs.actuator_pose &&
    lhs.joint_positions == rhs.joint_positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_lib::IKRequest_<ContainerAllocator1> & lhs, const ::arm_lib::IKRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_lib

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_lib::IKRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_lib::IKRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::IKRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::IKRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::IKRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::IKRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_lib::IKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c49257596f64e9170834568343a78b7";
  }

  static const char* value(const ::arm_lib::IKRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c49257596f64e91ULL;
  static const uint64_t static_value2 = 0x70834568343a78b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_lib::IKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_lib/IKRequest";
  }

  static const char* value(const ::arm_lib::IKRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_lib::IKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] actuator_pose\n"
"float64[] joint_positions\n"
;
  }

  static const char* value(const ::arm_lib::IKRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_lib::IKRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actuator_pose);
      stream.next(m.joint_positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IKRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_lib::IKRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_lib::IKRequest_<ContainerAllocator>& v)
  {
    s << indent << "actuator_pose[]" << std::endl;
    for (size_t i = 0; i < v.actuator_pose.size(); ++i)
    {
      s << indent << "  actuator_pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.actuator_pose[i]);
    }
    s << indent << "joint_positions[]" << std::endl;
    for (size_t i = 0; i < v.joint_positions.size(); ++i)
    {
      s << indent << "  joint_positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_LIB_MESSAGE_IKREQUEST_H
