// Generated by gencpp from file arm_lib/JointPose.msg
// DO NOT EDIT!


#ifndef ARM_LIB_MESSAGE_JOINTPOSE_H
#define ARM_LIB_MESSAGE_JOINTPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_lib
{
template <class ContainerAllocator>
struct JointPose_
{
  typedef JointPose_<ContainerAllocator> Type;

  JointPose_()
    : joint1(0.0)
    , joint2(0.0)
    , joint3(0.0)
    , joint4(0.0)
    , actuator_x(0.0)
    , actuator_y(0.0)
    , actuator_z(0.0)  {
    }
  JointPose_(const ContainerAllocator& _alloc)
    : joint1(0.0)
    , joint2(0.0)
    , joint3(0.0)
    , joint4(0.0)
    , actuator_x(0.0)
    , actuator_y(0.0)
    , actuator_z(0.0)  {
  (void)_alloc;
    }



   typedef float _joint1_type;
  _joint1_type joint1;

   typedef float _joint2_type;
  _joint2_type joint2;

   typedef float _joint3_type;
  _joint3_type joint3;

   typedef float _joint4_type;
  _joint4_type joint4;

   typedef float _actuator_x_type;
  _actuator_x_type actuator_x;

   typedef float _actuator_y_type;
  _actuator_y_type actuator_y;

   typedef float _actuator_z_type;
  _actuator_z_type actuator_z;





  typedef boost::shared_ptr< ::arm_lib::JointPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_lib::JointPose_<ContainerAllocator> const> ConstPtr;

}; // struct JointPose_

typedef ::arm_lib::JointPose_<std::allocator<void> > JointPose;

typedef boost::shared_ptr< ::arm_lib::JointPose > JointPosePtr;
typedef boost::shared_ptr< ::arm_lib::JointPose const> JointPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_lib::JointPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_lib::JointPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_lib::JointPose_<ContainerAllocator1> & lhs, const ::arm_lib::JointPose_<ContainerAllocator2> & rhs)
{
  return lhs.joint1 == rhs.joint1 &&
    lhs.joint2 == rhs.joint2 &&
    lhs.joint3 == rhs.joint3 &&
    lhs.joint4 == rhs.joint4 &&
    lhs.actuator_x == rhs.actuator_x &&
    lhs.actuator_y == rhs.actuator_y &&
    lhs.actuator_z == rhs.actuator_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_lib::JointPose_<ContainerAllocator1> & lhs, const ::arm_lib::JointPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_lib

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_lib::JointPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_lib::JointPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::JointPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::JointPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::JointPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::JointPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_lib::JointPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "839a73ecb0c0b015d4753a5736f4134c";
  }

  static const char* value(const ::arm_lib::JointPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x839a73ecb0c0b015ULL;
  static const uint64_t static_value2 = 0xd4753a5736f4134cULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_lib::JointPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_lib/JointPose";
  }

  static const char* value(const ::arm_lib::JointPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_lib::JointPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 joint1\n"
"float32 joint2\n"
"float32 joint3\n"
"float32 joint4\n"
"float32 actuator_x\n"
"float32 actuator_y\n"
"float32 actuator_z\n"
;
  }

  static const char* value(const ::arm_lib::JointPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_lib::JointPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint1);
      stream.next(m.joint2);
      stream.next(m.joint3);
      stream.next(m.joint4);
      stream.next(m.actuator_x);
      stream.next(m.actuator_y);
      stream.next(m.actuator_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_lib::JointPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_lib::JointPose_<ContainerAllocator>& v)
  {
    s << indent << "joint1: ";
    Printer<float>::stream(s, indent + "  ", v.joint1);
    s << indent << "joint2: ";
    Printer<float>::stream(s, indent + "  ", v.joint2);
    s << indent << "joint3: ";
    Printer<float>::stream(s, indent + "  ", v.joint3);
    s << indent << "joint4: ";
    Printer<float>::stream(s, indent + "  ", v.joint4);
    s << indent << "actuator_x: ";
    Printer<float>::stream(s, indent + "  ", v.actuator_x);
    s << indent << "actuator_y: ";
    Printer<float>::stream(s, indent + "  ", v.actuator_y);
    s << indent << "actuator_z: ";
    Printer<float>::stream(s, indent + "  ", v.actuator_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_LIB_MESSAGE_JOINTPOSE_H
