// Generated by gencpp from file three_arm_gazebo/AngleInputResponse.msg
// DO NOT EDIT!


#ifndef THREE_ARM_GAZEBO_MESSAGE_ANGLEINPUTRESPONSE_H
#define THREE_ARM_GAZEBO_MESSAGE_ANGLEINPUTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace three_arm_gazebo
{
template <class ContainerAllocator>
struct AngleInputResponse_
{
  typedef AngleInputResponse_<ContainerAllocator> Type;

  AngleInputResponse_()
    {
    }
  AngleInputResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::three_arm_gazebo::AngleInputResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::three_arm_gazebo::AngleInputResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AngleInputResponse_

typedef ::three_arm_gazebo::AngleInputResponse_<std::allocator<void> > AngleInputResponse;

typedef boost::shared_ptr< ::three_arm_gazebo::AngleInputResponse > AngleInputResponsePtr;
typedef boost::shared_ptr< ::three_arm_gazebo::AngleInputResponse const> AngleInputResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::three_arm_gazebo::AngleInputResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::three_arm_gazebo::AngleInputResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace three_arm_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::three_arm_gazebo::AngleInputResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::three_arm_gazebo::AngleInputResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::three_arm_gazebo::AngleInputResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::three_arm_gazebo::AngleInputResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::three_arm_gazebo::AngleInputResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::three_arm_gazebo::AngleInputResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::three_arm_gazebo::AngleInputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::three_arm_gazebo::AngleInputResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::three_arm_gazebo::AngleInputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "three_arm_gazebo/AngleInputResponse";
  }

  static const char* value(const ::three_arm_gazebo::AngleInputResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::three_arm_gazebo::AngleInputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::three_arm_gazebo::AngleInputResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::three_arm_gazebo::AngleInputResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AngleInputResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::three_arm_gazebo::AngleInputResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::three_arm_gazebo::AngleInputResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // THREE_ARM_GAZEBO_MESSAGE_ANGLEINPUTRESPONSE_H
