# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from three_arm_gazebo/JointAngles.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class JointAngles(genpy.Message):
  _md5sum = "7b58cc9c6acfc74729d0ca9f99d93c5a"
  _type = "three_arm_gazebo/JointAngles"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 jointOneAngle
float64 jointTwoAngle
float64 jointThreeAngle
float64 jointFourAngle"""
  __slots__ = ['jointOneAngle','jointTwoAngle','jointThreeAngle','jointFourAngle']
  _slot_types = ['float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       jointOneAngle,jointTwoAngle,jointThreeAngle,jointFourAngle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(JointAngles, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.jointOneAngle is None:
        self.jointOneAngle = 0.
      if self.jointTwoAngle is None:
        self.jointTwoAngle = 0.
      if self.jointThreeAngle is None:
        self.jointThreeAngle = 0.
      if self.jointFourAngle is None:
        self.jointFourAngle = 0.
    else:
      self.jointOneAngle = 0.
      self.jointTwoAngle = 0.
      self.jointThreeAngle = 0.
      self.jointFourAngle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.jointOneAngle, _x.jointTwoAngle, _x.jointThreeAngle, _x.jointFourAngle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.jointOneAngle, _x.jointTwoAngle, _x.jointThreeAngle, _x.jointFourAngle,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.jointOneAngle, _x.jointTwoAngle, _x.jointThreeAngle, _x.jointFourAngle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.jointOneAngle, _x.jointTwoAngle, _x.jointThreeAngle, _x.jointFourAngle,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
